Repository SixLabors/ImageSharp, pull requests merged in 2019-08, with the labels that each got.

#951 Add support for read and write tEXt, iTXt and zTXt chunks
  src/ImageSharp/Formats/Bmp/BmpCompression.cs
  src/ImageSharp/Formats/Gif/GifConstants.cs
  src/ImageSharp/Formats/Gif/GifDecoder.cs
  src/ImageSharp/Formats/Gif/GifDecoderCore.cs
  src/ImageSharp/Formats/Gif/GifEncoder.cs
  src/ImageSharp/Formats/Gif/GifEncoderCore.cs
  src/ImageSharp/Formats/Gif/GifFrameMetaData.cs
  src/ImageSharp/Formats/Gif/GifMetaData.cs
  src/ImageSharp/Formats/Gif/IGifDecoderOptions.cs
  src/ImageSharp/Formats/Gif/IGifEncoderOptions.cs
  src/ImageSharp/Formats/Png/IPngDecoderOptions.cs
  src/ImageSharp/Formats/Png/IPngEncoderOptions.cs
  src/ImageSharp/Formats/Png/PngChunkType.cs
  src/ImageSharp/Formats/Png/PngConstants.cs
  src/ImageSharp/Formats/Png/PngDecoder.cs
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  src/ImageSharp/Formats/Png/PngEncoder.cs
  src/ImageSharp/Formats/Png/PngEncoderCore.cs
  src/ImageSharp/Formats/Png/PngMetaData.cs
  src/ImageSharp/Formats/Png/PngTextData.cs
  src/ImageSharp/MetaData/ImageMetaData.cs
  src/ImageSharp/MetaData/ImageProperty.cs
  tests/ImageSharp.Sandbox46/Program.cs
  tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs
  tests/ImageSharp.Tests/Formats/Gif/GifMetaDataTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngMetaDataTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngTextDataTests.cs
  tests/ImageSharp.Tests/MetaData/ImageMetaDataTests.cs
  tests/ImageSharp.Tests/MetaData/ImagePropertyTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Gif/large_comment.gif
  tests/Images/Input/Png/InvalidTextData.png
  tests/Images/Input/Png/PngWithMetaData.png
  tests/Images/Input/Png/versioning-1_1.png
Labels: area:enhancement, area:formats:png

#955 #244 Add support for interlaced PNG encoding
  src/ImageSharp/Formats/Png/Adam7.cs
  src/ImageSharp/Formats/Png/IPngEncoderOptions.cs
  src/ImageSharp/Formats/Png/PngConstants.cs
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  src/ImageSharp/Formats/Png/PngEncoder.cs
  src/ImageSharp/Formats/Png/PngEncoderCore.cs
  src/ImageSharp/Formats/Png/PngEncoderHelpers.cs
  src/ImageSharp/Formats/Png/PngEncoderOptions.cs
  src/ImageSharp/Formats/Png/PngEncoderOptionsHelpers.cs
  src/ImageSharp/Formats/Png/PngInterlaceMode.cs
  src/ImageSharp/Formats/Png/PngMetaData.cs
  tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngMetaDataTests.cs
Labels: area:enhancement, area:formats:png

#957 fix some spelling
  src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs
  src/ImageSharp/Advanced/AdvancedImageExtensions.cs
  src/ImageSharp/Advanced/AotCompilerTools.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieLab.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieLuv.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/RGBPrimariesChromaticityCoordinates.cs
  src/ImageSharp/Common/Exceptions/UnknownImageFormatException.cs
  src/ImageSharp/Formats/Gif/GifEncoderCore.cs
  src/ImageSharp/Formats/Gif/LzwEncoder.cs
  src/ImageSharp/Formats/IImageFormatDetector.cs
  src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
  src/ImageSharp/IO/IFileSystem.cs
  src/ImageSharp/MetaData/Profiles/ICC/Enums/IccStandardObserver.cs
  src/ImageSharp/PixelFormats/PixelConversionModifiers.cs
  src/ImageSharp/Processing/KnownFilterMatrices.cs
  src/ImageSharp/Processing/KnownResamplers.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor{TPixel}.cs
  tests/ImageSharp.Benchmarks/Drawing/FillPolygon.cs
  tests/ImageSharp.Benchmarks/Drawing/FillRectangle.cs
  tests/ImageSharp.Tests/Advanced/AdvancedImageExtensionsTests.cs
  tests/ImageSharp.Tests/Drawing/DrawPathTests.cs
  tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs
  tests/ImageSharp.Tests/Drawing/FillSolidBrushTests.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPolygon.cs
  tests/ImageSharp.Tests/Drawing/Text/DrawText.cs
  tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/Block8x8FTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/LibJpegTools.SpectralData.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/ReferenceImplementations.LLM_FloatingPoint_DCT.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/ReferenceImplementations.StandardIntegerDCT.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/ReferenceImplementations.cs
  tests/ImageSharp.Tests/Image/ImageTests.Load_FromStream_ThrowsRightException.cs
  tests/ImageSharp.Tests/Memory/MemorySourceTests.cs
  tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataReader/IccDataReader.PrimitivesTests.cs
  tests/ImageSharp.Tests/Numerics/RationalTests.cs
  tests/ImageSharp.Tests/Processing/Effects/OilPaintTest.cs
  tests/ImageSharp.Tests/TestFont.cs
  tests/ImageSharp.Tests/TestFormat.cs
  tests/ImageSharp.Tests/TestUtilities/TestMemoryAllocator.cs
  tests/ImageSharp.Tests/TestUtilities/Tests/ImageComparerTests.cs
  tests/ImageSharp.Tests/TestUtilities/Tests/ReferenceDecoderBenchmarks.cs
Labels: area:documentation

#959 fix "as" usage
  src/ImageSharp/Advanced/AotCompilerTools.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.Curves.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.MultiProcessElement.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.TagDataEntry.cs
Labels: area:bug

#961 use params where possible
  tests/ImageSharp.Benchmarks/Drawing/DrawBeziers.cs
  tests/ImageSharp.Benchmarks/Drawing/DrawLines.cs
  tests/ImageSharp.Benchmarks/Drawing/DrawPolygon.cs
  tests/ImageSharp.Benchmarks/Drawing/FillPolygon.cs
  tests/ImageSharp.Benchmarks/Drawing/FillRectangle.cs
  tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs
  tests/ImageSharp.Tests/Issues/Issue412.cs
Labels: area:codequality

#962 fix some spelling
  src/ImageSharp/Formats/Gif/Sections/GifNetscapeLoopingApplicationExtension.cs
  src/ImageSharp/Memory/MemoryOwnerExtensions.cs
  src/ImageSharp/PixelFormats/PixelAlphaCompositionMode.cs
  src/ImageSharp/Primitives/Complex64.cs
  src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationSlidingWindowProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/TransformUtils.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_DivideRound.cs
  tests/ImageSharp.Benchmarks/Codecs/MultiImageBenchmarkBase.cs
  tests/ImageSharp.Benchmarks/Color/RgbToYCbCr.cs
  tests/ImageSharp.Benchmarks/General/BasicMath/ClampInt32IntoByte.cs
  tests/ImageSharp.Benchmarks/General/CopyBuffers.cs
  tests/ImageSharp.Benchmarks/General/Vectorization/UInt32ToSingle.cs
  tests/ImageSharp.Benchmarks/Samplers/Glow.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Formats/ImageFormatManagerTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.MetaData.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/ParseStreamTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/ReferenceImplementations.LLM_FloatingPoint_DCT.cs
  tests/ImageSharp.Tests/Formats/Jpg/Utils/ReferenceImplementations.cs
  tests/ImageSharp.Tests/Formats/Png/PngSmokeTests.cs
  tests/ImageSharp.Tests/GlobalSuppressions.cs
  tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.Generic.cs
  tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.NonGeneric.cs
  tests/ImageSharp.Tests/Image/ImageTests.Save.cs
  tests/ImageSharp.Tests/ImageOperationTests.cs
  tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataWriter/IccDataWriter.PrimitivesTests.cs
  tests/ImageSharp.Tests/Numerics/SignedRationalTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffFunctionsTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffFunctionsTests_TPixel.cs
  tests/ImageSharp.Tests/PixelFormats/Rgba32Tests.cs
  tests/ImageSharp.Tests/PixelFormats/RgbaVectorTests.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
  tests/ImageSharp.Tests/Processing/Transforms/ProjectiveTransformTests.cs
  tests/ImageSharp.Tests/Quantization/QuantizedImageTests.cs
  tests/ImageSharp.Tests/TestFormat.cs
  tests/ImageSharp.Tests/TestUtilities/ArrayHelper.cs
  tests/ImageSharp.Tests/TestUtilities/Attributes/ImageDataAttributeBase.cs
  tests/ImageSharp.Tests/TestUtilities/ImageComparison/ExactImageComparer.cs
  tests/ImageSharp.Tests/TestUtilities/ImageComparison/TolerantImageComparer.cs
  tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestImageProvider.cs
  tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestPatternProvider.cs
  tests/ImageSharp.Tests/TestUtilities/MeasureFixture.cs
  tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
Labels: area:documentation

#963 remove unused variables and methods
  src/ImageSharp/Advanced/AdvancedImageExtensions.cs
  src/ImageSharp/Common/Helpers/Guard.cs
  src/ImageSharp/Formats/Png/Filters/SubFilter.cs
  src/ImageSharp/MetaData/Profiles/Exif/ExifReader.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.Curves.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.NonPrimitives.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Gray16.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Gray8.cs
  src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs
  src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationSlidingWindowProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
  tests/ImageSharp.Benchmarks/General/Vectorization/UInt32ToSingle.cs
  tests/ImageSharp.Tests/Drawing/Paths/DrawPathCollection.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPath.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPathCollection.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPolygon.cs
  tests/ImageSharp.Tests/Drawing/Text/DrawText.cs
  tests/ImageSharp.Tests/Drawing/Text/DrawTextOnImageTests.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs
  tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.Generic.cs
  tests/ImageSharp.Tests/Image/ImageTests.DetectFormat.cs
  tests/ImageSharp.Tests/Image/ImageTests.Load_FileSystemPath_PassLocalConfiguration.cs
  tests/ImageSharp.Tests/Image/ImageTests.Load_FileSystemPath_UseDefaultConfiguration.cs
  tests/ImageSharp.Tests/Image/ImageTests.Load_FromBytes_PassLocalConfiguration.cs
  tests/ImageSharp.Tests/Image/ImageTests.Load_FromStream_ThrowsRightException.cs
  tests/ImageSharp.Tests/Image/ImageTests.Save.cs
  tests/ImageSharp.Tests/ImageOperationTests.cs
  tests/ImageSharp.Tests/MetaData/Profiles/Exif/ExifProfileTests.cs
  tests/ImageSharp.Tests/MetaData/Profiles/ICC/IccProfileTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs
  tests/ImageSharp.Tests/PixelFormats/Short4Tests.cs
  tests/ImageSharp.Tests/Primitives/DenseMatrixTests.cs
  tests/ImageSharp.Tests/Processing/Filters/BlackWhiteTest.cs
  tests/ImageSharp.Tests/Processing/Filters/ColorBlindnessTest.cs
  tests/ImageSharp.Tests/Processing/Filters/FilterTest.cs
  tests/ImageSharp.Tests/Processing/Filters/GrayscaleTest.cs
  tests/ImageSharp.Tests/Processing/Filters/InvertTest.cs
  tests/ImageSharp.Tests/Processing/Filters/KodachromeTest.cs
  tests/ImageSharp.Tests/Processing/Filters/LomographTest.cs
  tests/ImageSharp.Tests/Processing/Filters/PolaroidTest.cs
  tests/ImageSharp.Tests/Processing/Filters/SepiaTest.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeKernelMapTests.cs
  tests/ImageSharp.Tests/TestDataIcc/IccTestDataNonPrimitives.cs
  tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestImageProvider.cs
  tests/ImageSharp.Tests/TestUtilities/Tests/TestImageProviderTests.cs
Labels: area:codequality, area:performance

#990 Implement IDisposable in IImageProcessor<TPixel> instances.
  src/ImageSharp/Processing/DefaultImageProcessorContext{TPixel}.cs
  src/ImageSharp/Processing/IInternalImageProcessingContext{TPixel}.cs
  src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/BoxBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetector2DProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianSharpenProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Dithering/PaletteDitherProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Filters/LomographProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Filters/PolaroidProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/ICloningImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/IImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/ImageProcessorExtensions.cs
  src/ImageSharp/Processing/Processors/ImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/AutoOrientProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/EntropyCropProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/TransformProcessor.cs
  tests/ImageSharp.Tests/Drawing/Paths/DrawPathCollection.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPath.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPathCollection.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillPolygon.cs
  tests/ImageSharp.Tests/Drawing/Paths/FillRectangle.cs
  tests/ImageSharp.Tests/Drawing/Text/DrawText.cs
  tests/ImageSharp.Tests/Processing/BaseImageOperationsExtensionTest.cs
  tests/ImageSharp.Tests/Processing/FakeImageOperationsProvider.cs
  tests/ImageSharp.Tests/Processing/Filters/LomographTest.cs
  tests/ImageSharp.Tests/Processing/ImageOperationTests.cs
  tests/ImageSharp.Tests/Processing/ImageProcessingContextTests.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/BokehBlurTest.cs
Labels: area:api
