Repository SixLabors/ImageSharp, pull requests merged in 2019-05, with the labels that each got.

#906 Adds support for encoding 8-bit bitmaps
  src/ImageSharp/Formats/Bmp/BmpBitsPerPixel.cs
  src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
  src/ImageSharp/Formats/Bmp/BmpEncoder.cs
  src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs
  src/ImageSharp/Formats/Bmp/IBmpEncoderOptions.cs
  src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer.cs
  src/ImageSharp/Processing/Processors/Quantization/QuantizedFrame{TPixel}.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/ImageSharp.Tests/TestUtilities/PixelTypes.cs
  tests/Images/Input/Bmp/pal8gs.bmp
Labels: area:enhancement, area:formats:bmp

#916 Add Color overload to Pad method.
  src/ImageSharp/Processing/Extensions/PadExtensions.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/PadTest.cs
Labels: area:enhancement

#918 Removes usage of linq in several critical paths
  src/ImageSharp/Formats/Jpeg/Components/Decoder/ProfileResolver.cs
  src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
  src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs
  src/ImageSharp/Formats/Png/PngEncoderCore.cs
  src/ImageSharp/MetaData/Profiles/ICC/Curves/IccOneDimensionalCurve.cs
  src/ImageSharp/MetaData/Profiles/ICC/Curves/IccResponseCurve.cs
  src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs
  src/ImageSharp/MetaData/Profiles/ICC/MultiProcessElements/IccCurveSetProcessElement.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccChromaticityTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccColorantTableTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut16TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut8TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLutAToBTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLutBToATagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccMultiLocalizedUnicodeTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccMultiProcessElementsTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccNamedColor2TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccProfileSequenceDescTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccResponseCurveSet16TagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccUInt64ArrayTagDataEntry.cs
  src/ImageSharp/MetaData/Profiles/ICC/Various/IccClut.cs
  src/ImageSharp/MetaData/Profiles/ICC/Various/IccNamedColor.cs
  src/ImageSharp/MetaData/Profiles/ICC/Various/IccProfileDescription.cs
  src/ImageSharp/MetaData/Profiles/ICC/Various/IccProfileSequenceIdentifier.cs
  src/ImageSharp/Processing/ResizeOptions.cs
Labels: area:performance
