Repository SixLabors/ImageSharp, pull requests merged in 2019-12, with the labels that each got.

#1059 Allow returning the image format with the info.
  src/ImageSharp/Formats/Bmp/BmpImageFormatDetector.cs
  src/ImageSharp/Formats/Tga/TgaImageFormatDetector.cs
  src/ImageSharp/Image.Decode.cs
  src/ImageSharp/Image.FromStream.cs
  tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs
Labels: area:api, area:enhancement, area:formats

#1050 Public Vector4 to/from conversions
  src/ImageSharp/PixelFormats/PixelConversionModifiers.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Argb32.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgr24.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra32.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra5551.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb24.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb48.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba32.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba64.PixelOperations.Generated.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Generated/_Common.ttinclude
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.PixelOperations.cs
  src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.PixelOperations.cs
  src/ImageSharp/PixelFormats/PixelOperations{TPixel}.cs
Labels: area:api

#1066 Js/fix namespace
  README.md
  src/ImageSharp/Processing/Extensions/Binarization/BinaryDiffuseExtensions.cs
  src/ImageSharp/Processing/Extensions/Binarization/BinaryDitherExtensions.cs
  src/ImageSharp/Processing/Extensions/Binarization/BinaryThresholdExtensions.cs
  src/ImageSharp/Processing/Extensions/Convolution/BokehBlurExtensions.cs
  src/ImageSharp/Processing/Extensions/Convolution/BoxBlurExtensions.cs
  src/ImageSharp/Processing/Extensions/Convolution/DetectEdgesExtensions.cs
  src/ImageSharp/Processing/Extensions/Convolution/GaussianBlurExtensions.cs
  src/ImageSharp/Processing/Extensions/Convolution/GaussianSharpenExtensions.cs
  src/ImageSharp/Processing/Extensions/Dithering/DiffuseExtensions.cs
  src/ImageSharp/Processing/Extensions/Dithering/DitherExtensions.cs
  src/ImageSharp/Processing/Extensions/Effects/OilPaintExtensions.cs
  src/ImageSharp/Processing/Extensions/Effects/PixelateExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/BlackWhiteExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/BrightnessExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/ColorBlindnessExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/ContrastExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/FilterExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/GrayscaleExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/HueExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/InvertExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/KodachromeExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/LightnessExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/LomographExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/OpacityExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/PolaroidExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/SaturateExtensions.cs
  src/ImageSharp/Processing/Extensions/Filters/SepiaExtensions.cs
  src/ImageSharp/Processing/Extensions/Normalization/HistogramEqualizationExtensions.cs
  src/ImageSharp/Processing/Extensions/Overlays/BackgroundColorExtensions.cs
  src/ImageSharp/Processing/Extensions/Overlays/GlowExtensions.cs
  src/ImageSharp/Processing/Extensions/Overlays/VignetteExtensions.cs
  src/ImageSharp/Processing/Extensions/Quantization/QuantizeExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/AutoOrientExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/CropExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/EntropyCropExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/FlipExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/PadExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/ResizeExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/RotateExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/RotateFlipExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/SkewExtensions.cs
  src/ImageSharp/Processing/Extensions/Transforms/TransformExtensions.cs
  tests/ImageSharp.Benchmarks/Samplers/Diffuse.cs
  tests/ImageSharp.Tests/Processing/Dithering/DitherTest.cs
  tests/ImageSharp.Tests/Processing/Processors/Dithering/DitherTests.cs
Labels: area:bug
