Repository SixLabors/ImageSharp, pull requests merged in 2019-04, with the labels that each got.

#880 Nits - Colorspaces
  src/ImageSharp/ColorSpaces/CieXyChromaticityCoordinates.cs
  src/ImageSharp/ColorSpaces/Companding/GammaCompanding.cs
  src/ImageSharp/ColorSpaces/Companding/LCompanding.cs
  src/ImageSharp/ColorSpaces/Companding/Rec2020Companding.cs
  src/ImageSharp/ColorSpaces/Companding/Rec709Companding.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieLch.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CieXyzAndCieXyyConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CieXyzToLinearRgbConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CmykAndRgbConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/LinearRgbToRgbConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/RgbToLinearRgbConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/YCbCrAndRgbConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/WorkingSpaces/GammaWorkingSpace.cs
  tests/ImageSharp.Tests/Colorspaces/Companding/CompandingTests.cs
Labels: area:bug, area:colorspaces, area:performance

#874 Use more accuracy when calculating variance. Fix #866
  src/ImageSharp/Formats/Gif/GifEncoderCore.cs
  src/ImageSharp/Formats/Png/PngEncoderCore.cs
  src/ImageSharp/Processing/Processors/Quantization/FrameQuantizerBase{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/IFrameQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/QuantizeProcessor.cs
  src/ImageSharp/Processing/Processors/Quantization/WuFrameQuantizer{TPixel}.cs
  tests/ImageSharp.Tests/Quantization/WuQuantizerTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Png/low-variance.png
Labels: area:bug, area:quantizers

#891 Fix travis builds
  .travis.yml
Labels: area:build

#893 Pass correct output size source image is smaller than the Target in ResizeMode.Min
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeHelperTests.cs
Labels: area:bug

#887 Cleanup General Convolution
  src/ImageSharp.Drawing/Processing/PatternBrush{TPixel}.cs
  src/ImageSharp/Common/Helpers/DenseMatrixUtils.cs
  src/ImageSharp/Processing/Processors/Convolution/BoxBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetector2DProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianSharpenProcessor.cs
  src/ImageSharp/Processing/Processors/Dithering/ErrorDiffuserBase.cs
  tests/ImageSharp.Benchmarks/Samplers/GaussianBlur.cs
  tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataWriter/IccDataWriter.MatrixTests.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/BoxBlurTest.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/DetectEdgesTest.cs
Labels: area:api, area:bug, area:performance

#894 Faster Jpeg Huffman Decoding.
  src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
  src/ImageSharp/Formats/Jpeg/Components/Decoder/FastACTable.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanBuffer.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanTable.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/ScanDecoder.cs
  src/ImageSharp/Formats/Jpeg/JpegConstants.cs
  src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
  src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs
  src/ImageSharp/IO/DoubleBufferedStreamReader.cs
  src/ImageSharp/ImageSharp.csproj
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpeg_ImageSpecific.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DoubleBufferedStreams.cs
  tests/ImageSharp.Benchmarks/Codecs/MultiImageBenchmarkBase.cs
  tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj
  tests/ImageSharp.Tests/ImageSharp.Tests.csproj
Labels: area:formats:jpeg, area:performance

#883 ImageBrush shouldn't Dispose of the image it is using.
  src/ImageSharp.Drawing/Processing/ImageBrush{TPixel}.cs
  tests/ImageSharp.Tests/Drawing/FillImageBrushTests.cs
Labels: area:bug, area:drawing
