Repository SixLabors/ImageSharp, pull requests merged in 2020-09, with the labels that each got.

#1334 Add missing SaveAsync method
  .github/workflows/build-and-test.yml
  src/ImageSharp/Advanced/AdvancedImageExtensions.cs
  src/ImageSharp/ImageExtensions.cs
  tests/ImageSharp.Tests/Image/ImageTests.SaveAsync.cs
Labels: area:api, enhancement

#1314 Image.WrapMemory<TPixel> APIs wrapping Memory<byte>
  src/ImageSharp/Image.WrapMemory.cs
  src/ImageSharp/Memory/ByteMemoryManager{T}.cs
  src/ImageSharp/Memory/MemoryOwnerExtensions.cs
  src/ImageSharp/Processing/Processors/Dithering/OrderedDither.cs
  tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Labels: area:api, enhancement

#1333 Improved codegen in ImageSharp.Guard
  src/ImageSharp/Common/Helpers/Guard.cs
Labels: area:performance

#1337 Fix compatibility with NET 5 SDK InternalsVisibleTo
  src/Directory.Build.props
  src/Directory.Build.targets
  tests/ImageSharp.Tests/ImageSharp.Tests.csproj
Labels: area:build

#1343 Use interest for target bounds. Fixes #1342
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
Labels: area:transforms, bug
