Repository SixLabors/ImageSharp, pull requests merged in 2020-12, with the labels that each got.

#1464 Use correct shared ruleset path.
  tests/ImageSharp.Tests.ruleset
Labels: area:build

#1462 Implement PackFromRgbPlanes for Rgba32 and Rgb24
  src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs
  src/ImageSharp/Common/Helpers/SimdUtils.Pack.cs
  src/ImageSharp/Common/Helpers/SimdUtils.cs
  src/ImageSharp/ImageSharp.csproj
  src/ImageSharp/PixelFormats/PixelImplementations/PixelOperations/Rgb24.PixelOperations.cs
  src/ImageSharp/PixelFormats/PixelImplementations/PixelOperations/Rgba32.PixelOperations.cs
  src/ImageSharp/PixelFormats/PixelOperations{TPixel}.cs
  tests/ImageSharp.Benchmarks/General/PixelConversion/PixelConversion_PackFromRgbPlanes.cs
  tests/ImageSharp.Tests/Common/SimdUtilsTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs
Labels: area:performance

#1465 Optimize Convolution
  .gitattributes
  src/ImageSharp/Common/Helpers/DenseMatrixUtils.cs
  src/ImageSharp/Memory/Allocators/ArrayPoolMemoryAllocator.Buffer{T}.cs
  src/ImageSharp/Primitives/DenseMatrix{T}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DState.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionState.cs
  src/ImageSharp/Processing/Processors/Convolution/KernelSamplingMap.cs
  src/ImageSharp/Processing/Processors/Convolution/ReadOnlyKernel.cs
  tests/ImageSharp.Benchmarks/Config.cs
  tests/ImageSharp.Benchmarks/Samplers/GaussianBlur.cs
Labels: area:performance

#1475 Optimize bokeh blur convolution
  src/ImageSharp/Common/Helpers/Buffer2DUtils.cs
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/KernelSamplingMap.cs
  tests/ImageSharp.Benchmarks/Samplers/BokehBlur.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/BokehBlurTest.cs
  tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs
Labels: area:performance

#1477 1D convolution optimization and general codegen tweaks
  src/ImageSharp/ColorSpaces/Companding/SRgbCompanding.cs
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/PixelFormats/Utils/Vector4Converters.Default.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/BoxBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessorHelpers.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/GaussianSharpenProcessor{TPixel}.cs
Labels: area:performance

#1419 New Image.WrapMemory<TPixel>(void*) overloads
  src/ImageSharp/Image.WrapMemory.cs
  src/ImageSharp/Memory/ByteMemoryManager{T}.cs
  src/ImageSharp/Memory/UnmanagedMemoryManager{T}.cs
  tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Labels: API (proposal), feature request

#1481 Much Faster sRGB Companding
  src/ImageSharp/ColorSpaces/Companding/SRgbCompanding.cs
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/PixelFormats/Utils/Vector4Converters.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernel.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs
  tests/ImageSharp.Benchmarks/Processing/Resize.cs
  tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs
  tests/ImageSharp.Tests/TestUtilities/ApproximateFloatComparer.cs
Labels: area:performance
