Repository SixLabors/ImageSharp, pull requests merged in 2020-02, with the labels that each got.

#1104 Add new Color parsing methods.
  src/ImageSharp/Color/Color.NamedColors.cs
  src/ImageSharp/Color/Color.WernerPalette.cs
  src/ImageSharp/Color/Color.cs
  src/ImageSharp/PixelFormats/ColorConstants.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.Definitions.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs
  tests/ImageSharp.Benchmarks/Codecs/GetSetPixel.cs
  tests/ImageSharp.Benchmarks/Samplers/Diffuse.cs
  tests/ImageSharp.Benchmarks/Samplers/GaussianBlur.cs
  tests/ImageSharp.Benchmarks/Samplers/Rotate.cs
  tests/ImageSharp.Benchmarks/Samplers/Skew.cs
  tests/ImageSharp.Tests/Color/ColorTests.cs
  tests/ImageSharp.Tests/Color/ReferencePalette.cs
  tests/ImageSharp.Tests/Drawing/DrawImageTests.cs
  tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.Generic.cs
  tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.NonGeneric.cs
  tests/ImageSharp.Tests/Image/ImageTests.LoadPixelData.cs
  tests/ImageSharp.Tests/Image/ImageTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelBlenderTests.cs
  tests/ImageSharp.Tests/PixelFormats/Rgba32Tests.cs
  tests/ImageSharp.Tests/PixelFormats/UnPackedPixelTests.cs
  tests/ImageSharp.Tests/Processing/Overlays/GlowTest.cs
  tests/ImageSharp.Tests/Processing/Processors/Quantization/PaletteQuantizerTests.cs
  tests/ImageSharp.Tests/Processing/Transforms/ProjectiveTransformTests.cs
  tests/ImageSharp.Tests/Quantization/WuQuantizerTests.cs
  tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestPatternProvider.cs
Labels: area:api, area:enhancement

#1106 Break when minY >= bottom
  src/ImageSharp/Advanced/ParallelUtils/ParallelHelper.cs
  tests/ImageSharp.Tests/Helpers/ParallelHelperTests.cs
Labels: area:bug

#1108 WIP: single row value delegates for parallel iterator
  src/ImageSharp/Advanced/IRowAction.cs
  src/ImageSharp/Advanced/IRowAction{TBuffer}.cs
  src/ImageSharp/Advanced/ParallelRowIterator.cs
  src/ImageSharp/ImageFrame{TPixel}.cs
  src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs
  src/ImageSharp/Processing/Processors/Effects/OilPaintingProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Effects/PixelRowDelegateProcessor{TPixel,TDelegate}.cs
  src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Overlays/BackgroundColorProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Overlays/GlowProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/CropProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/FlipProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/RotateProcessor{TPixel}.cs
Labels: area:api, area:performance

#1112 Use Moment struct in WuQuantizer.
  src/ImageSharp/Processing/Processors/Quantization/WuFrameQuantizer{TPixel}.cs
Labels: area:codequality, area:enhancement, area:quantizers

#1113 Bokeh blur cache optimization
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Parameters/BokehBlurKernelData.cs
  src/ImageSharp/Processing/Processors/Convolution/Parameters/BokehBlurKernelDataProvider.cs
Labels: area:api, area:memory, area:performance

#1117 Removed unnecessary MemoryMarshal.Cast call
  src/ImageSharp/Formats/Jpeg/Components/Block8x8.cs
Labels: area:performance

#1128 Don't backpeddle when reading chunk lengths. Fix #1127
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Png/issues/Issue_1127.png
Labels: area:bug, area:formats:png

#1118 Faster Transforms
  src/ImageSharp/Common/Helpers/Guard.cs
  src/ImageSharp/Common/Helpers/ImageMaths.cs
  src/ImageSharp/Processing/AffineTransformBuilder.cs
  src/ImageSharp/Processing/Extensions/Transforms/TransformExtensions.cs
  src/ImageSharp/Processing/KnownResamplers.cs
  src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/CropProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/IResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/IResamplingTransformImageProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AutoOrientProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AutoOrientProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/FlipProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/FlipProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/LinearTransformUtilities.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/RotateProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/RotateProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/SkewProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/BicubicResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/BoxResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/CatmullRomResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/CubicResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/HermiteResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/Lanczos2Resampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/Lanczos3Resampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/Lanczos5Resampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/Lanczos8Resampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/LanczosResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/MitchellNetravaliResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/NearestNeighborResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/RobidouxResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/RobidouxSharpResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/SplineResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/TriangleResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resamplers/WelchResampler.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernel.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.PeriodicKernelMap.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs
  src/ImageSharp/Processing/Processors/Transforms/TransformKernelMap.cs
  src/ImageSharp/Processing/Processors/Transforms/TransformUtilities.cs
  src/ImageSharp/Processing/ProjectiveTransformBuilder.cs
  tests/ImageSharp.Benchmarks/Samplers/Diffuse.cs
  tests/ImageSharp.Benchmarks/Samplers/Rotate.cs
  tests/ImageSharp.Benchmarks/Samplers/Skew.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeKernelMapTests.ReferenceKernelMap.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeKernelMapTests.cs
  tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
  tests/ImageSharp.Tests/Processing/Transforms/PadTest.cs
  tests/ImageSharp.Tests/Processing/Transforms/ResizeTests.cs
  tests/ImageSharp.Tests/Processing/Transforms/TransformBuilderTestBase.cs
Labels: area:performance, area:transforms

#1131 Generic Octet<T> struct
  src/ImageSharp/Common/Helpers/SimdUtils.BasicIntrinsics256.cs
  src/ImageSharp/Common/Tuples/Octet.cs
  src/ImageSharp/Common/Tuples/Octet{T}.cs
  tests/ImageSharp.Benchmarks/General/PixelConversion/PixelConversion_Rgba32_To_Bgra32.cs
  tests/ImageSharp.Benchmarks/General/Vectorization/WidenBytesToUInt32.cs
Labels: area:api, area:codequality

#1130 Strong name all projects in the repository
  Directory.Build.props
  src/Directory.Build.props
  tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj
  tests/ImageSharp.Tests/AssemblyInfo.cs
  tests/ImageSharp.Tests/ImageSharp.Tests.csproj
Labels: area:build
