Repository SixLabors/ImageSharp, pull requests merged in 2020-08, with the labels that each got.

#1303 Optimize jpeg decoder based on traces.
  src/ImageSharp/Common/Helpers/SimdUtils.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanBuffer.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpeg_ImageSpecific.cs
Labels: area:performance, formats:jpeg

#1304 Simplify jpeg encoder and fix for Windows ARM
  Directory.Build.props
  src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
  src/ImageSharp/Formats/Jpeg/Components/Encoder/BlockQuad.cs
  src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbToYCbCrTables.cs
  src/ImageSharp/Formats/Jpeg/Components/Encoder/YCbCrForwardConverter{TPixel}.cs
  src/ImageSharp/Formats/Jpeg/Components/GenericBlock8x8.cs
  src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgb24.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/EncodeJpeg.cs
  tests/ImageSharp.Tests/Formats/Jpg/Block8x8FTests.cs
Labels: bug

#1328 Bump ChunkedMemoryStream buffer length
  .github/workflows/build-and-test.yml
  README.md
  src/ImageSharp/IO/ChunkedMemoryStream.cs
Labels: enhancement

#1332 Bokeh blur constructor tweaks (input validation, tiny speedup)
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/BokehBlurTest.cs
Labels: area:performance, bug
