Repository SixLabors/ImageSharp, pull requests merged in 2020-03, with the labels that each got.

#1146 Add overloads. Fix #1144
  src/ImageSharp/Image.FromBytes.cs
  src/ImageSharp/Image.FromFile.cs
  src/ImageSharp/Image.FromStream.cs
  tests/ImageSharp.Tests/Image/ImageTests.Identify.cs
  tests/ImageSharp.Tests/Image/ImageTests.ImageLoadTestBase.cs
Labels: area:api, area:enhancement

#1152 Replace Vector4.Clamp
  src/ImageSharp/ColorSpaces/Cmyk.cs
  src/ImageSharp/Common/Helpers/DenseMatrixUtils.cs
  src/ImageSharp/Common/Helpers/SimdUtils.FallbackIntrinsics128.cs
  src/ImageSharp/Common/Helpers/SimdUtils.cs
  src/ImageSharp/Common/Helpers/Vector4Utilities.cs
  src/ImageSharp/Formats/Jpeg/Components/Block8x8F.Generated.cs
  src/ImageSharp/Formats/Jpeg/Components/Block8x8F.Generated.tt
  src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Argb32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra4444.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra5551.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Byte4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/L16.cs
  src/ImageSharp/PixelFormats/PixelImplementations/L8.cs
  src/ImageSharp/PixelFormats/PixelImplementations/La16.cs
  src/ImageSharp/PixelFormats/PixelImplementations/La32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedByte4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedShort4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgb24.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgb48.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba1010102.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba64.cs
  src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Short4.cs
  src/ImageSharp/PixelFormats/Utils/Vector4Converters.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/LinearTransformUtilities.cs
  tests/ImageSharp.Benchmarks/General/BasicMath/ClampVector4.cs
  tests/ImageSharp.Tests/Helpers/Vector4UtilsTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs
Labels: area:performance

#1153 More Efficient ToBase64String
  src/ImageSharp/ImageExtensions.cs
Labels: area:enhancement

#1155 Add image extension method for save as tga
  src/ImageSharp/Formats/Tga/ImageExtensions.cs
  tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs
  tests/ImageSharp.Tests/Formats/ImageFormatManagerTests.cs
Labels: area:formats:tga

#1158 Gif. Use Buffer2D throughout.
  src/ImageSharp/Advanced/IPixelSource.cs
  src/ImageSharp/Common/Extensions/ComparableExtensions.cs
  src/ImageSharp/Formats/Gif/GifDecoderCore.cs
  src/ImageSharp/Formats/Gif/GifEncoderCore.cs
  src/ImageSharp/Formats/Gif/LzwDecoder.cs
  src/ImageSharp/Formats/Gif/LzwEncoder.cs
  src/ImageSharp/IndexedImageFrame{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/QuantizeProcessor{TPixel}.cs
  tests/ImageSharp.Tests/Quantization/QuantizedImageTests.cs
  tests/ImageSharp.Tests/Quantization/WuQuantizerTests.cs
Labels: area:enhancement, area:formats:gif
