Repository SixLabors/ImageSharp, pull requests merged in 2022-09, with the labels that each got.

#2220 Add option to encode 2-bit Bitmap's
  src/ImageSharp/Formats/Bmp/BmpBitsPerPixel.cs
  src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
  src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/ImageSharp.Tests/TestUtilities/ImageComparison/ImageComparer.cs
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecodeAlphaBitfields_Rgba32_rgba32abf.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_2Bit_Rgba32_pal2.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_2Bit_Rgba32_pal2color.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_9S.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_DIAMOND.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_GMARBLE.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_PINES.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_SKATER.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_SPADE.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_SUNFLOW.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_WARPD.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2BitmapArray_Rgba32_ba-bm.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2v2Header_Rgba32_pal8os2v2.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_Os2v2XShortHeader_Rgba32_pal8os2v2-16.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_RunLengthEncoded_24Bit_Rgba32_rgb24rle24.png
  tests/Images/External/ReferenceOutput/BmpDecoderTests/BmpDecoder_CanDecode_RunLengthEncoded_24Bit_Rgba32_rle24rlecut.png
  tests/Images/Input/Bmp/pal2.bmp
  tests/Images/Input/Bmp/pal2color.bmp
Labels: formats:bmp

#2192 Relaxed bmp dimensions validation
  src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
  src/ImageSharp/Formats/Bmp/BmpInfoHeader.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
Labels: formats:bmp

#2219 Implement Median Blur processor
  src/ImageSharp/Primitives/DenseMatrix{T}.cs
  src/ImageSharp/Processing/Extensions/Convolution/MedianBlurExtensions.cs
  src/ImageSharp/Processing/Processors/Convolution/Kernel.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianBlurProcessor.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianConvolutionState.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianRowOperation{TPixel}.cs
  tests/ImageSharp.Tests/Processing/Convolution/MedianBlurTest.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/MedianBlurTest.cs
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_CalliphoraPartial_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_CalliphoraPartial_5.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_Car_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_Car_5.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_blur_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/InBox_Rgba32_blur_5.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_CalliphoraPartial_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_CalliphoraPartial_5.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_Car_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_Car_5.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_blur_3.png
  tests/Images/External/ReferenceOutput/Convolution/MedianBlurTest/OnFullImage_Rgba32_blur_5.png
Labels: enhancement

#2225 Make TestFile Image threadsafe.
  tests/ImageSharp.Tests/TestFile.cs
Labels: test-bug

#2226 PNG filter improvements
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/Formats/Png/Filters/AverageFilter.cs
  src/ImageSharp/Formats/Png/Filters/NoneFilter.cs
  src/ImageSharp/Formats/Png/Filters/PaethFilter.cs
  src/ImageSharp/Formats/Png/Filters/SubFilter.cs
  src/ImageSharp/Formats/Png/Filters/UpFilter.cs
  tests/ImageSharp.Tests/Formats/Png/ReferenceImplementations.cs
Labels: area:performance

#2230 Fix for issue #2117
  .github/workflows/build-and-test.yml
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra32.cs
Labels: unit tests

#2233 Use System.Half for HalfTypeHelper
  src/ImageSharp/PixelFormats/HalfTypeHelper.cs
Labels: area:pixelformats, codequality

#2224 Add TryGetLinearlySeparableComponents and tests
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessorHelpers.cs
  tests/ImageSharp.Tests/Processing/Processors/Convolution/ConvolutionProcessorHelpersTest.cs
Labels: enhancement

#2241 Extend row operation interfaces with buffer length method
  src/ImageSharp/Advanced/IRowIntervalOperation{TBuffer}.cs
  src/ImageSharp/Advanced/IRowOperation{TBuffer}.cs
  src/ImageSharp/Advanced/ParallelRowIterator.Wrappers.cs
  src/ImageSharp/Advanced/ParallelRowIterator.cs
  src/ImageSharp/Processing/Processors/Binarization/AdaptiveThresholdProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2DRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianBlurProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/MedianRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Effects/PixelRowDelegateProcessor{TPixel,TDelegate}.cs
  src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Filters/OpaqueProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/AutoLevelProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Normalization/GrayscaleLevelsRowOperation{TPixel}.cs
  src/ImageSharp/Processing/Processors/Overlays/GlowProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs
  tests/ImageSharp.Tests/Helpers/ParallelRowIteratorTests.cs
  tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
Labels: API

#2245 Webp: Ignore unknown chunks, fixes #2243
  src/ImageSharp/Formats/Webp/WebpDecoderCore.cs
  tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Webp/issues/Issue2243.webp
Labels: formats:webp

#2249 Fix position handling in BufferedReadStream
  src/ImageSharp/IO/BufferedReadStream.cs
  tests/ImageSharp.Tests/IO/BufferedReadStreamTests.cs
Labels: bug
