Repository SixLabors/ImageSharp, pull requests merged in 2023-01, with the labels that each got.

#2313 Add byteLength to WrapMemory
  src/ImageSharp/Image.WrapMemory.cs
  tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Labels: API, breaking

#2322 Add DrawImage(Image, Point, Rectangle) method to the DrawImage processor
  src/ImageSharp/Processing/Extensions/Drawing/DrawImageExtensions.cs
  src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor.cs
  src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs
  tests/ImageSharp.Tests/Drawing/DrawImageTests.cs
  tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_10_10.png
  tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_25_50.png
  tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_50_25.png
  tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_50_50.png
Labels: enhancement, API

#2324 Allow zero DPI and only throw at EOF when not enough data
  src/ImageSharp/Formats/Jpeg/Components/Decoder/JFifMarker.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter.cs
  src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs
  src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
  tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs
  tests/ImageSharp.Tests/Formats/Jpg/JFifMarkerTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/SpectralJpegTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Jpg/issues/issue-2315.jpg
Labels: bug, formats:jpeg

#2325 Remove nullable disable from zlib
  src/ImageSharp/Compression/Zlib/DeflateThrowHelper.cs
  src/ImageSharp/Compression/Zlib/Deflater.cs
  src/ImageSharp/Compression/Zlib/DeflaterEngine.cs
  src/ImageSharp/Compression/Zlib/DeflaterHuffman.cs
  src/ImageSharp/Compression/Zlib/DeflaterOutputStream.cs
  src/ImageSharp/Compression/Zlib/DeflaterPendingBuffer.cs
  src/ImageSharp/Compression/Zlib/ZlibDeflateStream.cs
  src/ImageSharp/Compression/Zlib/ZlibInflateStream.cs
  src/ImageSharp/Diagnostics/MemoryDiagnostics.cs
  src/ImageSharp/Formats/Tiff/Compression/Decompressors/DeflateTiffCompression.cs
Labels: API, codequality

#2320 Remove #nullable disable from ExifProfile
  src/ImageSharp/Common/Helpers/UnitConverter.cs
  src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
  src/ImageSharp/Formats/Tiff/TiffBitsPerSample.cs
  src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs
  src/ImageSharp/Formats/Tiff/TiffDecoderMetadataCreator.cs
  src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs
  src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs
  src/ImageSharp/Formats/Tiff/TiffFrameMetadata.cs
  src/ImageSharp/Formats/Tiff/TiffThrowHelper.cs
  src/ImageSharp/Metadata/Profiles/Exif/ExifEncodedStringHelpers.cs
  src/ImageSharp/Metadata/Profiles/Exif/ExifProfile.cs
  src/ImageSharp/Metadata/Profiles/Exif/ExifReader.cs
  src/ImageSharp/Metadata/Profiles/Exif/ExifTagDescriptionAttribute.cs
  src/ImageSharp/Metadata/Profiles/Exif/ExifWriter.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifArrayValue{TValueType}.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifByte.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifByteArray.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifDouble.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifEncodedString.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifFloat.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifLong.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifLong8.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifLong8Array.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifNumber.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifNumberArray.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifRational.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifRationalArray.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifShort.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifShortArray.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifSignedByte.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifSignedShort.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifSignedShortArray.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifString.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifUcs2String.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValue.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValues.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValue{TValueType}.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/IExifValue.cs
  src/ImageSharp/Metadata/Profiles/Exif/Values/IExifValue{TValueType}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AutoOrientProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/TransformProcessorHelpers.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs
  tests/ImageSharp.Tests/Formats/Png/PngMetadataTests.cs
  tests/ImageSharp.Tests/Formats/Tiff/BigTiffDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderBaseTester.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs
  tests/ImageSharp.Tests/Formats/WebP/WebpMetaDataTests.cs
  tests/ImageSharp.Tests/Metadata/ImageMetadataTests.cs
  tests/ImageSharp.Tests/Metadata/Profiles/Exif/ExifProfileTests.cs
  tests/ImageSharp.Tests/Metadata/Profiles/Exif/ExifTagDescriptionAttributeTests.cs
  tests/ImageSharp.Tests/Metadata/Profiles/Exif/ExifValueTests.cs
  tests/ImageSharp.Tests/Processing/Transforms/TransformsHelpersTest.cs
  tests/ImageSharp.Tests/TestUtilities/ExifProfileExtensions.cs
Labels: API, codequality, breaking

#2326 Remove nullable disable from ColorSpace and Color
  src/ImageSharp/Color/Color.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.Adapt.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieXyz.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.cs
  src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverterOptions.cs
  src/ImageSharp/ColorSpaces/Conversion/Implementation/WorkingSpaces/RgbWorkingSpace.cs
Labels: API, codequality, breaking
