Repository SixLabors/ImageSharp, pull requests merged in 2023-02, with the labels that each got.

#2337 Remove nullable disable from pixelimplementations
  src/ImageSharp/PixelFormats/PixelImplementations/A8.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Abgr32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Argb32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgr24.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgr565.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Bgra4444.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Byte4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/HalfSingle.cs
  src/ImageSharp/PixelFormats/PixelImplementations/HalfVector2.cs
  src/ImageSharp/PixelFormats/PixelImplementations/HalfVector4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/L16.cs
  src/ImageSharp/PixelFormats/PixelImplementations/L8.cs
  src/ImageSharp/PixelFormats/PixelImplementations/La16.cs
  src/ImageSharp/PixelFormats/PixelImplementations/La32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedByte2.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedByte4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedShort2.cs
  src/ImageSharp/PixelFormats/PixelImplementations/NormalizedShort4.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rg32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgb24.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgb48.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba1010102.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Rgba64.cs
  src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Short2.cs
  src/ImageSharp/PixelFormats/PixelImplementations/Short4.cs
Labels: enhancement, API

#2338 Remove nullable disable from Processing.Processors
  src/ImageSharp/Formats/Gif/GifEncoderCore.cs
  src/ImageSharp/Processing/DefaultImageProcessorContext{TPixel}.cs
  src/ImageSharp/Processing/Processors/Convolution/KernelSamplingMap.cs
  src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor.cs
  src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/QuantizerOptions.cs
  src/ImageSharp/Processing/Processors/Quantization/QuantizerUtilities.cs
  src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
Labels: API, codequality

#2339 Added L16 support to tiff encoder
  src/ImageSharp/Formats/Tiff/Compression/HorizontalPredictor.cs
  src/ImageSharp/Formats/Tiff/Constants/TiffConstants.cs
  src/ImageSharp/Formats/Tiff/TiffBitsPerPixel.cs
  src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs
  src/ImageSharp/Formats/Tiff/TiffEncoderEntriesCollector.cs
  src/ImageSharp/Formats/Tiff/Writers/TiffColorWriterFactory.cs
  src/ImageSharp/Formats/Tiff/Writers/TiffGrayL16Writer{TPixel}.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Tiff/Calliphora_gray_deflate_16bit.tiff
  tests/Images/Input/Tiff/Calliphora_gray_deflate_predictor_16bit.tiff
  tests/Images/Input/Tiff/Calliphora_gray_lzw_predictor_16bit.tiff
  tests/Images/Input/Tiff/Calliphora_grayscale_uncompressed_16bit.tiff
  tests/Images/Input/Tiff/grayscale_uncompressed_16bit.tiff
Labels: formats:tiff

#2343 Restrict trigger for ARM to PRs containing labels only
  .github/workflows/build-and-test.yml
Labels: arch:arm64

#2344 Add ARM Intrinsics for PNG filters
  src/ImageSharp/Compression/Zlib/Adler32.cs
  src/ImageSharp/Compression/Zlib/Crc32.cs
  src/ImageSharp/Formats/Png/Filters/AverageFilter.cs
  src/ImageSharp/Formats/Png/Filters/PaethFilter.cs
  src/ImageSharp/Formats/Png/Filters/SubFilter.cs
  src/ImageSharp/Formats/Png/Filters/UpFilter.cs
  tests/ImageSharp.Tests/Formats/Png/Crc32Tests.cs
  tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs
  tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
Labels: arch:arm64

#2349 Actually call arm methods, if arm is supported
  src/ImageSharp/Compression/Zlib/Adler32.cs
  src/ImageSharp/Compression/Zlib/Crc32.cs
Labels: arch:arm32, arch:arm64

#2345 Remove nullable disable from Formats.BMP
  src/ImageSharp/Color/Color.cs
  src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
  src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs
  src/ImageSharp/Processing/Processors/Dithering/PaletteDitherProcessor{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer.cs
  src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer{TPixel}.cs
  src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs
Labels: API, breaking

#2355 Fix mode score calculation for SSE2/AVX2 version
  src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs
  src/ImageSharp/Formats/Webp/Lossy/QuantEnc.cs
  tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
Labels: bug, formats:webp

#2357 Allow setting configuration property
  src/ImageSharp/Formats/DecoderOptions.cs
  tests/ImageSharp.Tests/TestUtilities/ImageProviders/FileProvider.cs
Labels: API

#2360 Disable preEnumerateTheories for running tests
  tests/ImageSharp.Tests/xunit.runner.json
Labels: unit tests

#2356 Add ARM version of calculating mode scores
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs
  tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
Labels: formats:webp, arch:arm64

#2359 Enable Avx2 optimizations on Porter-Duff operations.
  src/ImageSharp/Common/Constants.cs
  src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs
  src/ImageSharp/Formats/Jpeg/Components/FloatingPointDCT.Intrinsic.cs
  src/ImageSharp/PixelFormats/PixelBlenders/DefaultPixelBlenders.Generated.cs
  src/ImageSharp/PixelFormats/PixelBlenders/DefaultPixelBlenders.Generated.tt
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.cs
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.tt
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.cs
  tests/ImageSharp.Benchmarks/PixelBlenders/PorterDuffBulkVsPixel.cs
  tests/ImageSharp.Benchmarks/PixelBlenders/PorterDuffBulkVsSingleVector.cs
  tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffCompositorTests.cs
  tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffFunctionsTests.cs
  tests/ImageSharp.Tests/TestUtilities/ApproximateFloatComparer.cs
  tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs
Labels: area:performance, area:pixelformats

#2365 Use compile time constants over method for all MMShuffle operations.
  src/ImageSharp/Common/Helpers/Shuffle/IComponentShuffle.cs
  src/ImageSharp/Common/Helpers/Shuffle/IPad3Shuffle4.cs
  src/ImageSharp/Common/Helpers/Shuffle/IShuffle3.cs
  src/ImageSharp/Common/Helpers/Shuffle/IShuffle4Slice3.cs
  src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs
  src/ImageSharp/Common/Helpers/SimdUtils.Shuffle.cs
  src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs
  src/ImageSharp/Formats/Webp/Lossy/Vp8Encoding.cs
  src/ImageSharp/PixelFormats/Utils/PixelConverter.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/Pad3Shuffle4Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle3Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle4Slice3Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/ShuffleByte4Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/ShuffleFloat4Channel.cs
  tests/ImageSharp.Tests/Common/SimdUtilsTests.Shuffle.cs
Labels: area:performance

#2369 Fix and normalize Vector4 UnPremultiply
  src/ImageSharp/Common/Helpers/Numerics.cs
  src/ImageSharp/Common/Helpers/Shuffle/IComponentShuffle.cs
  src/ImageSharp/Common/Helpers/Shuffle/IPad3Shuffle4.cs
  src/ImageSharp/Common/Helpers/Shuffle/IShuffle3.cs
  src/ImageSharp/Common/Helpers/Shuffle/IShuffle4Slice3.cs
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.cs
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.tt
  src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/PremultiplyVector4.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle3Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle4Slice3Channel.cs
  tests/ImageSharp.Benchmarks/Color/Bulk/UnPremultiplyVector4.cs
  tests/ImageSharp.Benchmarks/PixelBlenders/PorterDuffBulkVsPixel.cs
  tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs
  tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_DestOut.png
  tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_In.png
  tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_Out.png
Labels: area:performance

#2371 Rewrite ColorMatrix
  src/ImageSharp/Common/Helpers/ColorNumerics.cs
  src/ImageSharp/Diagnostics/CodeAnalysis/UnscopedRefAttribute.cs
  src/ImageSharp/Primitives/ColorMatrix.Impl.cs
  src/ImageSharp/Primitives/ColorMatrix.cs
  tests/ImageSharp.Benchmarks/Bulk/ColorMatrixTransforms.cs
  tests/ImageSharp.Benchmarks/Bulk/FromRgba32Bytes.cs
  tests/ImageSharp.Benchmarks/Bulk/FromVector4.cs
  tests/ImageSharp.Benchmarks/Bulk/FromVector4_Rgb24.cs
  tests/ImageSharp.Benchmarks/Bulk/Pad3Shuffle4Channel.cs
  tests/ImageSharp.Benchmarks/Bulk/PremultiplyVector4.cs
  tests/ImageSharp.Benchmarks/Bulk/Rgb24Bytes.cs
  tests/ImageSharp.Benchmarks/Bulk/Shuffle3Channel.cs
  tests/ImageSharp.Benchmarks/Bulk/Shuffle4Slice3Channel.cs
  tests/ImageSharp.Benchmarks/Bulk/ShuffleByte4Channel.cs
  tests/ImageSharp.Benchmarks/Bulk/ShuffleFloat4Channel.cs
  tests/ImageSharp.Benchmarks/Bulk/ToRgba32Bytes.cs
  tests/ImageSharp.Benchmarks/Bulk/ToVector4.cs
  tests/ImageSharp.Benchmarks/Bulk/ToVector4_Bgra32.cs
  tests/ImageSharp.Benchmarks/Bulk/ToVector4_Rgb24.cs
  tests/ImageSharp.Benchmarks/Bulk/ToVector4_Rgba32.cs
  tests/ImageSharp.Benchmarks/Bulk/UnPremultiplyVector4.cs
  tests/ImageSharp.Benchmarks/Bulk/Vector4Factory.cs
  tests/ImageSharp.Benchmarks/General/GetSetPixel.cs
  tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj
  tests/ImageSharp.Benchmarks/Processing/BokehBlur.cs
  tests/ImageSharp.Tests/Primitives/ColorMatrixTests.cs
Labels: area:performance

#2373 Automatically push the build to NuGet on a tagged release
  .github/workflows/build-and-test.yml
Labels: area:build
