Repository SixLabors/ImageSharp, pull requests merged in 2024-04, with the labels that each got.

#2699 Ensure VP8X alpha flag is updated correctly.
  src/ImageSharp/Common/Helpers/RiffHelper.cs
  src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs
  src/ImageSharp/Formats/Webp/Chunks/WebpVp8X.cs
  src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs
  src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs
  src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs
  src/ImageSharp/Formats/Webp/WebpDecoderCore.cs
  src/ImageSharp/Formats/Webp/WebpEncoderCore.cs
Labels: bug, formats:webp

#2703 V4 Ensure VP8X alpha flag is updated correctly.
  src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs
  src/ImageSharp/Formats/Webp/Chunks/WebpVp8X.cs
  src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs
  src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs
  src/ImageSharp/Formats/Webp/RiffHelper.cs
  src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs
  src/ImageSharp/Formats/Webp/WebpDecoderCore.cs
  src/ImageSharp/Formats/Webp/WebpEncoderCore.cs
Labels: bug, formats:webp

#2718 Limit Read Palette Indices
  src/ImageSharp/Formats/Png/PngScanlineProcessor.cs
  tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Png/issues/Issue_2714.png
Labels: bug, formats:png

#2719 V2 - Limit Read Palette Indices
  src/ImageSharp/Formats/Png/PngScanlineProcessor.cs
  tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Png/issues/Issue_2714.png
Labels: bug, formats:png

#2706 Limit all memory allocations in the MemoryAllocator layer
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  src/ImageSharp/Memory/Allocators/Internals/UnmanagedMemoryHandle.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs
  src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs
  src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroup{T}.cs
  src/ImageSharp/Memory/InvalidMemoryOperationException.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Buffer2DTests.cs
  tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.Allocate.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Bmp/issue-2696.bmp
Labels: security

#2717 V2 - Clear Pixel Buffers on Decode.
  src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs
  src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
Labels: security

#2716 Clear Pixel Buffers on Decode.
  src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs
  src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
Labels: security

#2715 V2 - Limit all memory allocations in the MemoryAllocator layer
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  src/ImageSharp/Memory/Allocators/Internals/UnmanagedMemoryHandle.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs
  src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs
  src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroup{T}.cs
  src/ImageSharp/Memory/InvalidMemoryOperationException.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Buffer2DTests.cs
  tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.Allocate.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Bmp/issue-2696.bmp
Labels: security

#2720 Merge latest release from v3
  src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs
  src/ImageSharp/Formats/Png/PngDecoderCore.cs
  src/ImageSharp/Formats/Png/PngScanlineProcessor.cs
  src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
  src/ImageSharp/Memory/Allocators/Internals/UnmanagedMemoryHandle.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs
  src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs
  src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs
  src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroup{T}.cs
  src/ImageSharp/Memory/InvalidMemoryOperationException.cs
  tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs
  tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
  tests/ImageSharp.Tests/Memory/Buffer2DTests.cs
  tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.Allocate.cs
  tests/ImageSharp.Tests/TestImages.cs
  tests/Images/Input/Bmp/issue-2696.bmp
  tests/Images/Input/Png/issues/Issue_2714.png
Labels: bug, security
